export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_ERROR: 'GET_INGREDIENTS_ERROR' = 'GET_INGREDIENTS_ERROR';

export const SET_BUN_COUNTER: 'SET_BUN_COUNTER' = 'SET_BUN_COUNTER';
export const RESET_BUN_COUNTER: 'RESET_BUN_COUNTER' = 'RESET_BUN_COUNTER';
export const INCREASE_INGREDIENT_COUNTER: 'INCREASE_INGREDIENT_COUNTER' = 'INCREASE_INGREDIENT_COUNTER';
export const DECREASE_INGREDIENT_COUNTER: 'DECREASE_INGREDIENT_COUNTER' = 'DECREASE_INGREDIENT_COUNTER';